[package]
name = "rcgen"
version = "0.0.2"
authors = ["est31 <MTest31@outlook.com>"]
description = "Rust X.509 certificate generator"
repository = "https://github.com/est31/rcgen"
documentation = "https://docs.rs/rcgen"
license = "MIT/Apache-2.0"

[lib]
name = "rcgen"
path = "src/lib.rs"

[[bin]]
name = "rcgen"
path = "src/main.rs"

[dependencies]
#yasna = "0.1"
yasna = { git = "https://github.com/est31/yasna.rs", rev = "c4a54d90133ca22453ae01bd024ff5d834aa2997" }
#yasna = { path = "../yasna.rs" }
bit-vec = "0.5"
ring = "0.14.0-alpha4"
untrusted = "0.6"
pem = "0.5"
chrono = "0.4.6"
