[package]
name = "rcgen"
version = "0.0.2"
authors = ["est31 <MTest31@outlook.com>"]
description = "Rust X.509 certificate generator"
repository = "https://github.com/est31/rcgen"
documentation = "https://docs.rs/rcgen"
license = "MIT/Apache-2.0"
readme = "README.md"

[lib]
name = "rcgen"
path = "src/lib.rs"

[[bin]]
name = "rcgen"
path = "src/main.rs"

[dependencies]
yasna = { version = "0.2", features = ["chrono", "bit-vec"] }
bit-vec = "0.5"
ring = "0.13"
untrusted = "0.6"
pem = "0.5"
chrono = "0.4.6"

[dev-dependencies]
openssl = "0.10"
webpki = "0.18.1"
