name: ci

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly, stable 7 months ago]
        exclude:
          - os: macOS-latest
            toolchain: beta
          - os: macOS-latest
            toolchain: nightly
          - os: macOS-latest
            toolchain: stable 7 months ago

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Run cargo check --all
      env:
        RUSTFLAGS: -D warnings
      run: |
        cargo check --all
    - name: Run the tests
      env:
        RUSTFLAGS: -D warnings
      run: |
         cargo test --all
    - name: Run the tests with x509-parser enabled
      env:
        RUSTFLAGS: -D warnings
      run: |
         cargo test --verbose --features x509-parser
    - name: Run cargo doc
      run: |
        cargo doc --all --all-features
